package pe.edu.examen.unsch.entities;
// Generated Jul 7, 2019 10:47:07 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Semestre generated by hbm2java
 */
@Entity
@Table(name = "semestre", catalog = "cargabd")
public class Semestre implements java.io.Serializable {

	private int idSemestre;
	private Docente docente;
	private String nombreSemestre;
	private int numeroHora;

	public Semestre() {
	}

	public Semestre(int idSemestre, Docente docente, String nombreSemestre, int numeroHora) {
		this.idSemestre = idSemestre;
		this.docente = docente;
		this.nombreSemestre = nombreSemestre;
		this.numeroHora = numeroHora;
	}

	@Id

	@Column(name = "id_semestre", unique = true, nullable = false)
	public int getIdSemestre() {
		return this.idSemestre;
	}

	public void setIdSemestre(int idSemestre) {
		this.idSemestre = idSemestre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "docente_id_docente", nullable = false)
	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

	@Column(name = "nombre_semestre", nullable = false, length = 45)
	public String getNombreSemestre() {
		return this.nombreSemestre;
	}

	public void setNombreSemestre(String nombreSemestre) {
		this.nombreSemestre = nombreSemestre;
	}

	@Column(name = "numero_hora", nullable = false)
	public int getNumeroHora() {
		return this.numeroHora;
	}

	public void setNumeroHora(int numeroHora) {
		this.numeroHora = numeroHora;
	}

}
